config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'user_sessions#index'

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :todo_items

  validates :title, presence: true
  validates :title, length: { minimum: 3 }

  def has_completed_items?
    todo_items.complete.size > 0
  end

  def has_incomplete_items?
    todo_items.incomplete.size > 0
  end 
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :require_user
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :set_back_link, except: [:index]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    def set_back_link
      go_back_link_to todo_lists_path
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list, builder: FoundationFormBuilder) do |f| %>
  <%= f.text_field :title, label: "List Title", autofocus: 'autofocus' %>

  <%= f.submit "Save" %>    
<% end %>

app/views/todo_lists/edit.html.erb
<%= title "Editing #{@todo_list.title}" %>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'List Veiw', todo_lists_path %>

app/views/todo_lists/index.html.erb
<%= title "Todo Lists" %>

<ul class="list todo-lists no-bullet">
<% @todo_lists.each do |todo_list| %>
  <li id="<%= dom_id(todo_list) %>" class="clearfix">
    <%= link_to todo_list_todo_items_path(todo_list), class: "row" do %>
      <div class="small-10 medium-11 columns truncate" title="<%= todo_list.title %>"><%= todo_list.title %></div>
      <div class="small-2 medium-1 columns"><span class="label round"><%= todo_list.todo_items.size %></span></div>
    <% end %>
  </li>
<% end %>
</ul>

app/views/todo_lists/new.html.erb
<%= title "Add a Todo List" %>

<%= render 'form' %>

app/views/todo_lists/show.html.erb
<%= title @todo_list.title %>

<% if @todo_list.has_incomplete_items? %>
<h3>Incomplete Items:</h3>

<ul>
  <% @todo_list.todo_items.incomplete.each do |todo_item| %>
  <li><%= todo_item.content %></li>
  <% end %>
</ul>
<% end %>

<% if @todo_list.has_completed_items? %>
<h3>Complete Items:</h3>

<ul>
  <% @todo_list.todo_items.complete.each do |todo_item| %>
  <li><%= todo_item.content %></li>
  <% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>